spring:
  application:
    name: LockingOptimisticPessmistic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Madhav@2021
    url: jdbc:mysql://localhost:3306/ordersdb
    username: root
  jpa:
  
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect